<?php

namespace \cache\proxies\__CG__\core\model;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Grupo extends \core\model\Grupo implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setNome($nome)
    {
        $this->__load();
        return parent::setNome($nome);
    }

    public function getNome()
    {
        $this->__load();
        return parent::getNome();
    }

    public function getDescricao()
    {
        $this->__load();
        return parent::getDescricao();
    }

    public function setDescricao($descricao)
    {
        $this->__load();
        return parent::setDescricao($descricao);
    }

    public function toString()
    {
        $this->__load();
        return parent::toString();
    }

    public function getLeft()
    {
        $this->__load();
        return parent::getLeft();
    }

    public function setLeft($left)
    {
        $this->__load();
        return parent::setLeft($left);
    }

    public function getRight()
    {
        $this->__load();
        return parent::getRight();
    }

    public function setRight($right)
    {
        $this->__load();
        return parent::setRight($right);
    }

    public function getParent()
    {
        $this->__load();
        return parent::getParent();
    }

    public function setParent(\core\model\TreeModel $parent)
    {
        $this->__load();
        return parent::setParent($parent);
    }

    public function isRoot()
    {
        $this->__load();
        return parent::isRoot();
    }

    public function isChild(\core\model\TreeModel $parent)
    {
        $this->__load();
        return parent::isChild($parent);
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function __tostring()
    {
        $this->__load();
        return parent::__tostring();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'nome', 'descricao', 'left', 'right', 'parentId', 'id');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}