<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Symfony\UX\StimulusBundle\StimulusBundle::class => ['all' => true],
    Symfony\UX\Turbo\TurboBundle::class => ['all' => true],
    Twig\Extra\TwigExtraBundle\TwigExtraBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    Symfony\Bundle\MercureBundle\MercureBundle::class => ['all' => true],
    Novosga\AttendanceBundle\NovosgaAttendanceBundle::class => ['all' => true],
    Novosga\MonitorBundle\NovosgaMonitorBundle::class => ['all' => true],
    Novosga\ReportsBundle\NovosgaReportsBundle::class => ['all' => true],
    Novosga\SchedulingBundle\NovosgaSchedulingBundle::class => ['all' => true],
    Novosga\SettingsBundle\NovosgaSettingsBundle::class => ['all' => true],
    Novosga\TriageBundle\NovosgaTriageBundle::class => ['all' => true],
    Novosga\UsersBundle\NovosgaUsersBundle::class => ['all' => true],
    Symfony\UX\Icons\UXIconsBundle::class => ['all' => true],
    League\Bundle\OAuth2ServerBundle\LeagueOAuth2ServerBundle::class => ['all' => true],
    Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle::class => ['dev' => true, 'test' => true],
];
