#!/bin/sh
### BEGIN INIT INFO
# Provides:          painel
# Author:            Rogerio Lino <rogeriolino.com>
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Script para iniciar o servidor de painel do Novo SGA
### END INIT INFO


# PATH should only include /usr/* if it runs after the mountnfs.sh script
DESC="Servidor de painel do Novo SGA"
NAME=painel
SCRIPTNAME=/etc/init.d/$NAME
DIRNAME=/opt/novosga-painel-server
PIDFILE="pid.txt"

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
#. /lib/lsb/init-functions


start_painel() {
    echo "Iniciando servidor painel do Novo SGA..."
    cd $DIRNAME
    if [ -f $PIDFILE ] 
    then
        echo "O servidor já está em execução"
    else
        ./server.sh 2> /var/log/novosga-painel-server &
        echo "Servidor iniciado com sucesso!"
    fi
    return 1
}

stop_painel() {
    echo "Parando o servidor de painel do Novo SGA..."
    cd $DIRNAME
    if [ -f $PIDFILE ] 
    then
        PID=$(cat $PIDFILE) 
        kill $PID
        rm $PIDFILE
        echo "Servidor parado com sucesso!"
    else
        echo "Processo não encontrado em execução"
    fi
    return 1
}

restart_painel() {
    stop_painel 
    start_painel
    return 1
}

case $1 in
    start)
        start_painel
    ;;
    stop)
        stop_painel
    ;;
    restart)
        restart_painel
    ;;
    *)
        echo $DESC
        echo "Uso: /etc/init.d/$NAME {start|stop|restart}"
        exit 1
    ;;
esac

exit 0
